name: 🔨 Build RootHidePatcher

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    name: 🍎 Build & Package
    runs-on: macos-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 📦 Install Build Dependencies
        run: |
          brew install ldid dpkg make

      - name: 🚀 Execute Build Command
        run: |
          chmod +x ./build.command
          ./build.command

      - name: 📤 Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RootHidePatcher-Binaries
          path: |
            **/*.ipa
            **/*.tipa
            **/*.deb
          if-no-files-found: error
